"""create_all_models

Revision ID: 7e937aa93846
Revises: 
Create Date: 2026-06-06 20:09:42.849247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e937aa93846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('structure_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_units_id'), 'structure_units', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEPARTMENT_HEAD', 'ART_DIRECTOR', 'EMPLOYEE', name='role'), nullable=False),
    sa.Column('su_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['su_id'], ['structure_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ON_APPROVAL', 'APPROVED', 'REJECTED', 'PLANNED', 'COMPLETED', name='event_status'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('event_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('CREATED', 'ON_APPROVAL', 'APPROVED', 'REJECTED', 'PLANNED', 'COMPLETED', name='event_status'), nullable=True),
    sa.Column('new_status', sa.Enum('CREATED', 'ON_APPROVAL', 'APPROVED', 'REJECTED', 'PLANNED', 'COMPLETED', name='event_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_history_id'), 'event_history', ['id'], unique=False)
    # ### end Alembic commands ###


    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "INSERT INTO structure_units (name, address) "
            "VALUES ('МУ ЦКиД Факел', 'г. Фрязино, ул. Вокзальная д. 2') RETURNING id"
        )
    )
    su_id = result.scalar_one()

    conn.execute(
        sa.text(
            "INSERT INTO users (full_name, email, hashed_password, role, su_id) "
            "VALUES (:full_name, :email, :hashed_password, :role, :su_id)"
        ),
        {
            "full_name": "Администратор",
            "email": "admin@example.com",
            "hashed_password": "$2b$12$iXFk12LuZUNQ4o2MlDALVOPxccwyG3qoUCJoipMYT7/vEbZZCE9Lq",
            "role": "ADMIN",
            "su_id": su_id,
        },
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_history_id'), table_name='event_history')
    op.drop_table('event_history')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_structure_units_id'), table_name='structure_units')
    op.drop_table('structure_units')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
